# Generated by Django 3.1.1 on 2021-11-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flatnum',
            field=models.CharField(max_length=50),
        ),
    ]
