# Generated by Django 3.1.1 on 2021-11-13 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_auto_20211113_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='ondate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
