# Generated by Django 3.1.1 on 2021-11-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_association_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='flatnum',
            field=models.CharField(max_length=50),
        ),
    ]
