# Generated by Django 3.1.1 on 2021-12-01 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_auto_20211119_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaintype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Familymember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('cell', models.BigIntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.gender')),
                ('memberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.owner')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.relation')),
            ],
        ),
        migrations.CreateModel(
            name='ComplainRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flatno', models.IntegerField()),
                ('complaintdesc', models.CharField(max_length=50)),
                ('serviceprovider', models.CharField(max_length=50)),
                ('blockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.block')),
                ('complaintype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.complain')),
            ],
        ),
    ]
