# Generated by Django 3.1.1 on 2022-01-29 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_auto_20220129_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='datetimeout',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 10, 9, 29, 952106)),
        ),
    ]
