# Generated by Django 3.2.5 on 2023-03-03 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_auto_20230303_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingslot',
            name='ontime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='datetimeout',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 14, 43, 50, 953373)),
        ),
    ]
